### PR TITLE
Forgot password page

### PR DESCRIPTION
**Pull request by Ahad1317**
ahad

### CODE REVIEW

**Review by kunalkeshan — CHANGES_REQUESTED** [review]
The design looks cool buddy. There are some small changes to make though. 

## Use PNPM, having clashing lock files fails the deployment process. 

Delete the `package-lock.json` and use `pnpm i` instead. If you don't have `pnpm` installed use `npm i -g pnpm` to install it. Do this for the root and the client folder.

## Update Image in Forgot Password Page 

For the Image in the forgot password page, make it full width similar to the login and signup page. Like this
image

## Test for Responsiveness

Do make sure that the code is responsive as well. 

## Revert Change for `Landing.tsx`

Place Navbar and Landing Page content back into this page. 

```tsx
const Landing = () => {
	return (
		<>
			<Navbar />
			<main className='w-full px-5'>
				<Intro />
				<Features />
			</main>
			<Footer />
		</>
	);
};
```

A route for the Forgot Password Page has already been added, so it can be checked out in the `/forgot-password` route. This exists in the `/client/src/App.tsx` file.

**Review by kunalkeshan — CHANGES_REQUESTED** [review]
Remove unused components from `Landing.tsx`

Here's the Vercel Logs for why the build is failing. 

```txt
[23:33:55.044] Running build in Washington, D.C., USA (East) – iad1 (Hive)
[23:33:55.150] Cloning github.com/kunalkeshan/Social-Sphere (Branch: aa/feat/forgotpasswordpage, Commit: 587997c)
[23:33:55.499] Cloning completed: 349.296ms
[23:33:55.769] Previous build caches not available
[23:33:55.967] Running "vercel build"
[23:33:56.426] Vercel CLI 32.4.1
[23:33:57.133] Detected `pnpm-lock.yaml` version 6 generated by pnpm 8
[23:33:57.139] Installing dependencies...
[23:33:57.753] Lockfile is up to date, resolution step is skipped
[23:33:57.782] Progress: resolved 1, reused 0, downloaded 0, added 0
[23:33:57.904] Packages: +334
[23:33:57.905] ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
[23:33:58.786] Progress: resolved 334, reused 0, downloaded 85, added 72
[23:33:59.789] Progress: resolved 334, reused 0, downloaded 125, added 111
[23:34:00.789] Progress: resolved 334, reused 0, downloaded 218, added 207
[23:34:01.792] Progress: resolved 334, reused 0, downloaded 332, added 321
[23:34:02.792] Progress: resolved 334, reused 0, downloaded 334, added 333
[23:34:06.034] Progress: resolved 334, reused 0, downloaded 334, added 334
[23:34:06.035] Progress: resolved 334, reused 0, downloaded 334, added 334, done
[23:34:06.291] .../esbuild@0.17.19/node_modules/esbuild postinstall$ node install.js
[23:34:06.383] .../esbuild@0.17.19/node_modules/esbuild postinstall: Done
[23:34:06.515] 
[23:34:06.515] dependencies:
[23:34:06.515] + @emotion/react 11.11.0
[23:34:06.515] + @emotion/styled 11.11.0
[23:34:06.516] + @fontsource/roboto 4.5.8
[23:34:06.516] + @mui/icons-material 5.11.16
[23:34:06.516] + @mui/material 5.13.1
[23:34:06.516] + @reduxjs/toolkit 1.9.5
[23:34:06.516] + autoprefixer 10.4.14
[23:34:06.516] + axios 1.4.0
[23:34:06.516] + lottie-react 2.4.0
[23:34:06.516] + postcss 8.4.23
[23:34:06.516] + react 18.2.0
[23:34:06.516] + react-dom 18.2.0
[23:34:06.516] + react-hot-toast 2.4.1
[23:34:06.516] + react-query 3.39.3
[23:34:06.516] + react-redux 8.0.5
[23:34:06.516] + react-router-dom 6.11.2
[23:34:06.516] + tailwindcss 3.3.2
[23:34:06.516] 
[23:34:06.516] devDependencies:
[23:34:06.516] + @types/node 20.2.5
[23:34:06.516] + @types/react 18.0.28
[23:34:06.516] + @types/react-dom 18.0.11
[23:34:06.516] + @typescript-eslint/eslint-plugin 5.57.1
[23:34:06.516] + @typescript-eslint/parser 5.57.1
[23:34:06.517] + @vitejs/plugin-react 4.0.0
[23:34:06.517] + eslint 8.38.0
[23:34:06.517] + eslint-plugin-react-hooks 4.6.0
[23:34:06.517] + eslint-plugin-react-refresh 0.3.4
[23:34:06.517] + typescript 5.0.2
[23:34:06.517] + vite 4.3.2
[23:34:06.517] 
[23:34:06.533] Done in 9.3s
[23:34:06.576] Running "pnpm run build"
[23:34:07.086] 
[23:34:07.086] > social-sphere-client@0.0.0 build /vercel/path0/client
[23:34:07.086] > tsc && vite build
[23:34:07.086] 
[23:34:11.717] src/pages/Landing.tsx(10,1): error TS6133: 'ForgotPasswordPage' is declared but its value is never read.
[23:34:11.718] src/pages/Landing.tsx(11,1): error TS6133: 'Login' is declared but its value is never read.
[23:34:11.737]  ELIFECYCLE  Command failed with exit code 2.
[23:34:11.756] Error: Command "pnpm run build" exited with 1
```

**Comment by Ahad1317** [comment]
image

**Comment by Ahad1317** [comment]
Mobile view :

127 0 0 1_5173_forgot-password(iPhone SE)

@kunalkeshan tab view images for login and sign up is also vertically stretched. what say ?

127 0 0 1_5173_forgot-password(iPad Mini)

**Review by kunalkeshan — CHANGES_REQUESTED** [review]
Can you reuse the same input styling as the login and signup page, it's being inconsistent with the other pages with the current style. 

In desktop view you can hide the side image as done in the login/signup page.

**Review by kunalkeshan — APPROVED** [review]

**Pull request closed without merging**
